/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package go;

import java.awt.Graphics;

/**
 *
 * @author tvtuttle
 */
public class GoPanel extends javax.swing.JPanel {
    Controller theController;
    int boardSize;
    /**
     * Creates new form GoPanel
     */
    public GoPanel() {
        initComponents();
        setVisible(true);
    }
    public GoPanel(int goSize){
        initComponents();
        setVisible(true);
//        theController = new Controller(goSize);
        boardSize = goSize;
        startUp();
        
        
//        repaint();
    }
    
    void startUp(){
        theController = new Controller(boardSize);
        theController.setPanel(this);
        theController.start();
        repaint();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        theController.paint(g);
//        theBoard.paint(g);
//        System.out.println("painting theBoard = " + theBoard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        passButton = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        trainButton.setText("Train");
        trainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainButtonActionPerformed(evt);
            }
        });
        add(trainButton);
        trainButton.setBounds(50, 10, 63, 25);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        add(resetButton);
        resetButton.setBounds(120, 10, 100, 25);

        passButton.setText("Pass");
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });
        add(passButton);
        passButton.setBounds(230, 10, 100, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void trainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainButtonActionPerformed
        // TODO add your handling code here:
        theController.train(100);
    }//GEN-LAST:event_trainButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        theController.handleClicked(evt.getX(), evt.getY());
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
//        theController.reset();
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    public void reset(){
        startUp();
//        theController.reset();
        repaint();
    }
    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        // TODO add your handling code here:
        theController.pass();
    }//GEN-LAST:event_passButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton passButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton trainButton;
    // End of variables declaration//GEN-END:variables
}
